services:
  
  # 服务名
  paas:
    # 模拟一个伪终端
    tty: true
    # 打开标准输入,可以接受外部输入
    stdin_open: true
    # 主机名
    hostname: paas
    # 指定容器名称
    container_name: paas
    # 构建镜像
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    # 指定为镜像名称或镜像ID
    image: danxiaonuo/cmdb-paas:latest
    # 覆盖容器启动后默认执行的命令
    # command: /sbin/init
    # entrypoint: ["tail", "-f", "/dev/null"]
    # 允许容器中运行一些特权命令
    privileged: true
    # 指定容器退出后的重启策略为始终重启
    restart: always
    # 指定容器的内核能力(capacity)分配
    cap_add:
     - ALL
    env_file:
       - ./.env_vars/.env_db_mysql
       - ./.env_vars/.env_paas
    # 数据卷所挂载路径设置
    volumes:
      # 数据目录
      # - ./data:/data:rw,cached
      # 同步宿主机时区与时间
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro,cached
      - /etc/localtime:/etc/localtime:ro,cached
      # 共享内核
      - /lib/modules:/lib/modules:ro,cached
      # 共享系统配置
      - /etc/sysctl.conf:/etc/sysctl.conf:ro,cached
    # 解决容器的依赖
    #depends_on:
    #  - ""
    # 环境变量
    # environment:
    # 配置容器连接的网络
    network_mode: "host"
    # 指定容器的 ulimits 限制值
    ulimits:
      nproc: 65535
      nofile:
          soft: 65535
          hard: 65535
